name: Build

on:
  push

jobs:
  build:
    name: build-and-test-${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Build
      if: runner.os == 'Windows'
      run: ./build.ps1 build
    - name: Build
      if: runner.os == 'Linux'
      run: ./build.sh build

    - name: Test
      if: runner.os == 'Windows'
      run: ./build.ps1 test
    - name: Test
      if: runner.os == 'Linux'
      run: ./build.sh test
